name: Code Quality

on:
  push:
    branches: [ "master", "cicd-init" ]
  pull_request:
    branches: [ "master", "cicd-init" ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package, flake8, and requirements
        run: |
          python -m pip install --upgrade pip==24.0
          python -m pip install flake8==7.0.0 flake8-bugbear==24.4.21
          python -m pip install numpy
          python -m pip install sipyco@git+https://github.com/m-labs/sipyco.git
          python ./setup.py
          python -m pip install .
